### PR TITLE
DISABLE_SCREEN_FRAME disabling black borders too

### PR DESCRIPTION
**Pull request by domenicomuti**
Hi, I think this is a useful mod for the ones that want to completely disable the frame and the black borders.
I also made some cleaning in the function tsample removing the parameters offs and resolution because they're not used in function.

### CODE REVIEW

**Comment by mattiasgustavsson** [comment]
I'm not so sure about this change - it is doing more than just removing the borders, it is also removing the curvature part of the CRT effect, which is something I consider part of the distinct look it has. Also, I am not sure why, maybe it is just a scaling issue, but the screen seems overall a bit too bright after this change (the shader is a bit tricky to tweak though, as various effects have weird dependency on others). 

In the long term, the way I would really like to solve this, is by finally implementing the currently unused `config` part of the shader (https://github.com/mattiasgustavsson/dos-like/blob/6c813f371b1f8ad34e455aa64bba6c6677793973/source/libs/crtemu_pc.h#L30). This could allow users to tweak the look of the CRT filter in many different ways, including having more or less curvature. But I wouldn't like to tie it in with the existing DISABLE_SCREEN_FRAME switch.

**Comment by domvhscrap** [comment]
You're right, i removed the curvature, because to me doesn't make sense after removing the frame. I also tweaked the vignette effect when i removed the frame, maybe that's why you it seem brighter to you.

**Comment by domvhscrap** [comment]
In the past days i tried the config part, then i figured that it's doing nothing :)

**Comment by mattiasgustavsson** [comment]
> In the past days i tried the config part, then i figured that it's doing nothing :)

Yeah, it's been on my TODO list for a long long time.. Any month now... 😝

**Comment by mattiasgustavsson** [comment]
Thinking some more on this, I think my only real objection is that it is piggy-backing on the existing DISABLE_SCREEN_FRAME switch, and thus changing the behavior of that too much (and I know there are some who expects the current behavior).

If it was on its own switch, like DISABLE_CRT_CURVE maybe, then it would be fine (and yeah, disabling the curve would implicitly disable the frame as well, but that's fine as it is a new switch). Oh, and overall brightness should be of a comparable level, perceptually. Just leaving the vignette as is, is probably easiest, or otherwise tweaking overall brightness so it looks about the same. 

I would also prefer leaving the unused params in there for now - just because it will make it easier for me to manage merging different versions of the code in the future, and it is not really needed for disabling the curve anyway.

What do you think?

**Comment by domvhscrap** [comment]
I think you're right. I added the new switch DISABLE_CRT_CURVE and I correct the overall brightness, now looks the same!

**Comment by mattiasgustavsson** [comment]
I think the DISABLE_CRT_CURVE could sort of make sense, but seeing as this evolved into disabling CRT emulation alltogether, I think it is too big a change for dos-like, and I think it is better off as a fork. I feel like disabling the CRT doesn't really work, as the aspect ratio is then wrong in some mode (in particular modes like 640x200, but also some text modes suffer). While it could probably be fixed, by writing a custom scaler, something like crtemu but without the crt emulation, just the scaling, it would be a bit more work. I also feel like the CRT look is very much a part of dos-likes identity, so yeah, I feel like it is better off as a fork rather than part of the main version.

**Pull request closed without merging**
